### ISSUE TITLE
vites js compatibility

### ISSUE THREAD

**Issue by jeje42** [ts-arch/ts-arch#56]
Hi,

Did anyone try to run ts-arch within a vite js project?

 I just tried to copy the test from the README file and setting test timeout globally to 60000 (https://vitest.dev/config/#testtimeout) but I get error "TypeError: message is not a function".

**Comment by torfmaster** [comment]
Hi,

I didn't try, yet. Would you mind creating a (more or less) minimal repo to reproduce the error?

**Comment by jeje42** [comment]
Hi,

I tried again lately and it appears to work.

I created a template project anyway at https://github.com/jeje42/ts-arch-vitest, in case this might be useful to anyone.
