### ISSUE TITLE
Help: Restrict Usage of Date Class

### ISSUE THREAD

**Issue by sashokbg** [ts-arch/ts-arch#74]
Hello, for out project we are using joda-js time and I wish to completely restrict the usage of Date class.
I could not find how to do it, since Date is in global scope and is not imported the usual way.

Thank you for your advice
Best Regards
Aleks

**Comment by c-harding** [comment]
This project won’t be able to help with that, as it only scans imports. Have you tried eslint? There is a rule [`no-restricted-globals`](https://eslint.org/docs/latest/rules/no-restricted-globals), with which you should be able to block `Date`.
